import Head from 'next/head'
import MainLayout from '../src/components/layout/main-layout'
import '../styles/globals.sass'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  )
}

export default MyApp
